### ISSUE TITLE
Continue with CKEditor docs

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/T3DocTeam#25]
Riccardo De Contardi has started. Now we need to find out how to continue best.

From Slack Jul 14, 2018:
https://typo3.slack.com/archives/C028JEPJL/p1531580665000030

Riccardo De Contardi [5:04 PM]
Hello guys. I've just finished to write down my findings about CKEditor plugins here https://docs.typo3.org/typo3cms/drafts/github/T3DocumentationStarter/Public-Info-002/HelloWorld/Index.html
This is far from finished, but it is the best I can do...
Apart from formatting (I'm not sure that everything is ok) there are at least two great issues to solve
- descriptions: I cut and pasted the description of each plugin from the CKEditor site; I don't know if it is good or they should be rewritten
- there are a lot of TDB and alert blocks, each time I was not sure about what to write or I got stuck
Feel free to contact me if you need something, I will try to help further as I can

Martin Bless [7:25 PM]
@riccardodecontardi Thank you very much. Great, that you managed to do that in that starter project. I'll look at it and then find a way for the next steps.

Riccardo De Contardi [9:04 PM]
@martin.bless let me know if I can help

Martin Bless [9:05 PM]
didn't start yet

**Comment by sypets** [comment]
@marble @Riccardo Please note that there is already a forge issue for documenting rte_ckeditor: https://forge.typo3.org/issues/85461

See also what Benni wrote about what should go in system extension docs (in core) and what in Core API (see the forge issue).

There is a DRAFTs area for rte_ckeditor, which could be used to work on it: https://docs.typo3.org/typo3cms/Teams/T3DocTeam/Drafts/rte_ckeditor/rte_ckeditor/Documentation/Index.html

It can then be used for a core patch. 

If you don't want to use the DRAFTS area, just delete it or let me know and I'll delete it. 

Benni already wrote some notes for rte_ckeditor. I think @DanielSiepmann said he will start to convert them to reST.

I think it would be a good idea to finish a minimal version (so that we will finally have some documentation at all) and work on more extensive changes in another patch.

**Comment by DanielSiepmann** [comment]
The work of benni is available at https://docs.google.com/document/d/13C9qi3NR2KJikX9ziGg1Pkg59bLR_JwC9yz6YpA6v54/edit?usp=sharing

**Comment by DanielSiepmann** [comment]
Next steps would be to export the drive document as open office, to migrate it to restructured text via the rendering toolchain.
The result will be merged with Riccardos work.

The generated extension manual draft will be rendered in the draft area of docs.typo3.org.
Afterwards someone else from the community can jump in and improve the state of the documentation.

This can then be merged to TYPO3 CMS repository as documentation of the system extension.

**Comment by marble** [comment]
From the Etherpad https://notes.typo3.org/p/T3DocTeam-Sprint-2018-07-2

Somebody wrote:

- I think it is necessary to have an official documentation about CKEditor configuration and customization...

- Consider https://github.com/NamelessCoder/fluid-documentation-generator to generate documentation site for core packages

**Comment by sypets** [comment]
As mentioned in the issue (https://forge.typo3.org/issues/85461?next_issue_id=85456), the text by Benni should be split up:

Benni: "I propose this:

1. Base Principles of RTEs and transformations, yaml configuration concepts in [Core API:RTE](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Rte/Index.html)
2. integration of CKEditor into extension manual ("how do i set up a custom CKEditor module etc")"

**Comment by sypets** [comment]
Draft for splitting up structure to "rte_ckeditor" docs + "TYPO3 explained": 

**Toc of Googledoc Benni document and where text should be moved**

- [ ] About CKEditor v4 &rarr; **rte_ckeditor: Introduction**
  - [ ] Integration in TYPO3 &rarr; **rte_ckeditor: Introduction**
- [ ] TYPO3 Rich Text Editing API &rarr; **rte_ckeditor: General concepts**
  - [ ] Editor Configuration
  - [ ] Transformations &rarr; **short section in rte_ckeditor docs and link to [TYPO3 Explained RTE Transformations](https://docs.typo3.org/typo3cms/CoreApiReference/latest/ApiOverview/Rte/Transformations/Index.html)**
      - A brief dive into history
   - [ ] Frontend Output
     - TypoScript
     - Fluid
- [ ] Configuration &rarr; **rte_ckeditor: Introduction**
  - Historical usage of PageTSconfig as configuration format
  - Yaml as new configuration format &rarr; **todo: in "TYPO3 Explained"**
  - Features within Yaml configuration files for TYPO3 &rarr; **todo: in "TYPO3 Explained"**
    - File Imports
    - Placeholders
    - Appending yaml lists
    - [ ] Coding Guidelines for yaml files &rarr;  **todo [TYPO3 Explained](https://docs.typo3.org/typo3cms/CoreApiReference/CodingGuidelines/Index.html#)**
  - [ ] Configuration Presets &rarr; rte_ckeditor
  - [ ] Overriding configuration via PageTSconfig
  - [ ] Best Practices for Custom Configurations &rarr;  **should be in TYPO3 explained as well?**
    - [ ] Use a custom extension / site extension
    - [ ] Use TYPO3’s Core Default.yaml as boilerplate
    - [ ] Use Core includes
  - [ ] Transformations vs. CKEditor’s Advanced Content Filter
- RTE Configuration Reference &rarr; **rte_ckeditor: Configuration/Reference**
  - Processing
  - Editor
- Frequently Asked Questions
  - CKEditor - Common Configuration Needs
  - How do I customize the toolbar?
  - What are stylesets?
  - How can I configure classes to anchor tags?
  - What is the contents.css?
  - How can I set specific classes for anchors?
  - How can I extend custom tags?
  - How can I add images?
  - How can I add custom plugins?
  - How can I configure tables?
  - How can I add more attributes to anchor tags?
  - How can I allow / deny specific tags?
  - How to add custom styles for ul tags?
  - Migrating from HtmlArea
    - Output in the frontend is different
    - How do I have “mutually exclusive classes”?

**Comment by sypets** [comment]
Patch is in review: https://review.typo3.org/c/59627/

About the patch:
* most parts based on [Google Doc by Bennie Mack ](https://docs.google.com/document/d/1arnGOG0phFSyjeeZrf05gZ_MN0imO898bfVCKygYyUA/edit?usp=sharing)
* some general information was to be moved to "TYPO3 Explained". As for now, I left most of the information in the rte_ckeditor docs, because more expertise is required to review the information on [RTE in TYPO3 Explained](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Rte/Index.html) (and I don't have enough expertise on that to do it) and merge with new information. I think this can be done in a second step.
* added some new text, mostly:
  * [list of features in introduction](https://review.typo3.org/c/59627/8/typo3/sysext/rte_ckeditor/Documentation/Introduction/Index.rst#48)
  * created ["Configuration: Example"](https://review.typo3.org/c/59627/8/typo3/sysext/rte_ckeditor/Documentation/Configuration/Examples.rst) page from list of FAQ questions and answered some of them
  * Added ["Basic Usage"](https://review.typo3.org/c/59627/8/typo3/sysext/rte_ckeditor/Documentation/Usage/Index.rst)
* docs is still missing some diagrams and more configuration examples. 
* Additional general information about configuration has been moved to a new Google doc: https://docs.google.com/document/d/1mWrPncnfqkZZnNp8zda161Xy0k3tIZV-nGSMUC7HPaU/edit?usp=sharing. I think this can be merged with some of my work in [this open pull request](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/364) and added to TYPO3 Explained later. 


Even though there is still work to be done, I believe the patch is mergable in its current form.

**Comment by sypets** [comment]
This is pretty much done. See:

* docs online: https://docs.typo3.org/typo3cms/extensions/rte_ckeditor/
* news entry: https://docs.typo3.org/News/2019/Index.html#news-2019-02-14

Still open: PR for adding link in "Tell me Something About": https://github.com/TYPO3-Documentation/TYPO3CMS-TellMeSomethingAbout/pull/9

**Comment by sypets** [comment]
Still todo: 

* add links to rte_ckeditor documentation in other manuals:

* [x] Sybille: Getting started tutorial
* [ ]  Tutorial for editors
* [ ]  TYPO3 Explained

* [ ] Check and update section about [RTE](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Rte/Index.html) in TYPO3 Explained

* [ ] Sybille: Move some general information about configuration to [general configuration documentation](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/408) (in progess)

@josefglatz Please let me know if you are working on any of this
