### ISSUE TITLE
Define responsibilities of the Documentation Team

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/T3DocTeam#26]
Which tasks are covered by the Documentation Team?

This should be discussed and defined during the sprint.

Afterwards the result should be updated at:
- https://forge.typo3.org/projects/team-docteam
- https://typo3.org/community/teams/documentation/
- https://docs.typo3.org/typo3cms/Teams/T3DocTeam/

**Comment by DanielSiepmann** [comment]
- Provide info about how to write documentation.
- Be there for others to answer questions.
- Be available in the team leader channel.
- Provide rendering of official manuals and extensions.
- Sprints.
- Promote the work / press work.

Not responsible for:
- Translations, of manuals.
- https://wiki.typo3.org/
- https://api.typo3.org/

**Comment by DanielSiepmann** [comment]
@marble will move the work to the drafts area of the team document. Then a text will be built from the collected points. The text will then be proof read and published in the team document.

**Comment by sypets** [comment]
I am updating https://forge.typo3.org/projects/team-docteam **responsibilities** because that is just outdated and should at least reflect current status (not responsible for translation, wiki and api.typo3.org). 

Actually, I think that info should probably go on team page on typo3.org but a new text should first go through a drafts and review process and I would like to just make some quick changes now to at least get things up to date.

# Old text:

* Official documentation
* Support Translation of manuals
* Administration of api.typo3.org
* Administration of wiki.typo3.org
ReStructured Text Infrastructure

![wiki](https://user-images.githubusercontent.com/13206455/52478763-af78b600-2ba6-11e9-87fc-038c11900828.png)


New text: 

https://forge.typo3.org/projects/team-docteam

**Comment by sypets** [comment]
Team page has been updated, "responsibilities" were added: https://typo3.org/community/teams/documentation/
