### ISSUE TITLE
Find a way: Give credit and acknowledgements to authors - discussion

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/T3DocTeam#30]
**Update**: This issue can be used for **discussion** about topic. 

To make suggestions or show solutions, please add them to #95
---

How do we want to handle this? Let's develop a solution over time.

Example ① of a pragmatic solution:

Discussion about how to give credit at [slack](https://typo3.slack.com/archives/C028JEPJL/p1533059719000341). Topic: *Tutorial to turn legacy installations into composer based installations.* See [installation guide](https://docs.typo3.org/typo3cms/InstallationGuide/MigrateToComposer/Index.html), [tweet](https://twitter.com/marantern/status/1024307898359406592)

**Comment by marble** [comment]
Example discussion about how to give credit https://typo3.slack.com/archives/C028JEPJL/p1533059719000341 . In this case: Tutorial to turn legacy installations into composer based installations. See [installation guide](https://docs.typo3.org/typo3cms/InstallationGuide/MigrateToComposer/Index.html), [tweet](https://twitter.com/marantern/status/1024307898359406592)

**Comment by marble** [comment]
Random example from the Python world:
https://docs.python.org/2.3/lib/node282.html

![grafik](https://user-images.githubusercontent.com/307057/43486105-38b12590-9513-11e8-8ac1-b6564129ce1e.png)

**Comment by sypets** [comment]
What we already have: 

1) The developer appreciation page contains a section about documentation contributors as well, I think since April 2018:

https://typo3.com/blog/april-2018-developer-appreciation-day-dad/

2) List of contributors on github, e.g. https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/graphs/contributors and of course in the commit messages

3) In some manuals, Author is listed, usually main author on start page and additional authors in Preface or Introduction under credits, e.g. see [Getting Started Tutorial](https://docs.typo3.org/typo3cms/GettingStartedTutorial/)

![start](https://user-images.githubusercontent.com/13206455/57699530-3763d580-7658-11e9-8f36-1e18684badf3.png)

![credits](https://user-images.githubusercontent.com/13206455/57699550-45b1f180-7658-11e9-8666-0c25280284b3.png)


(What I don't mean with this comment is that we shouldn't do more. Just wanted to list what is already being done).

**Comment by marble** [comment]
From [slack](https://typo3.slack.com/archives/C028JEPJL/p1533109511000318)

Sybille Peters [9:45 AM]
I think it's good to give credit. But giving everyone credit in the text where it is due and not forgetting someone is not so easy. For Albrecht's contribution: How about a news message on docs.typo3.org (maybe even on typo3.org or this month in TYPO3  where several smaller and larger contributions could be bundled into one news entry). I think it's a pity that the docs are not mentioned at all in last month in TYPO3. And I agree, we should make contribution more visible. The "site package tutorial" has Michael Schams as author, so we do mention individuals (even though other people have contributed and will contribute more over time).

Some links: 
this month in typo3: https://typo3.org/project/news/this-month-in-typo3/this-month-in-typo3-july-2018-issue-4/
documentation news: https://docs.typo3.org/News/Index.html (edited)

Stephan Großberndt [9:45 AM]
beer:for @koehnlein
Hey @botty! What's up?

Daniel Siepmann [9:47 AM]
There is a place where the contributions to code and docs are mentioned, just can't find it

Sybille Peters [9:48 AM]
https://typo3.com/blog/april-2018-developer-appreciation-day-dad/
TYPO3 GmbH
April 2018: Developer Appreciation Day (DAD)
Welcome back for another analysis of contributions to TYPO3 CMS over the last month: It’s Developer Appreciation Day (DAD)! We’re really grateful for having so many hardworking and engaged devs among us - thanks a lot! Find April’s most important names and some truly impressive numbers in our recent blog post.
https://typo3.com/fileadmin/user_upload/developer_appreciation_day_april_2018_header_image.jpg
developer appreciation page. Contains mention of contribution to docs as well, I think since April 2018.

Daniel Siepmann [9:48 AM]
yes ;)
And this is already auto generated from github
So no way to forget someone

Martin Bless [10:59 AM]
Except the author isn't the one that made the PR

**Comment by sypets** [comment]
Please also see Mattes'  suggestion on decisions for showing contribution in commit messages, because it is very similar to the topic raised in this issue: https://decisions.typo3.org/t/visualize-contribution-in-commit-messages/384/32

**Comment by schams-net** [comment]
Some thoughts you might consider:

➀ If someone writes an entire manual (tutorial, guide, etc.) from scratch, he/she is the **author** and deserves to be clearly stated as such.  
➁ If someone extends or updates an existing manual *significantly*, this is likely a **contribution**, and he/she should be listed, e.g. in a section "Acknowledgment" or "Contributors".  
➂ If someone reviews a manual, reports issues, makes comments, small corrections or small suggestions, this is part of **community work**. Credits should be given by the owner/maintainer, e.g. a personal "thank you!" or an entry in the Git merge message.

The above relates to **unpaid work** and to documentation only. If someone is paid to review a text or to write a documentation, the credits should be negotiated before work commences.

**Comment by sypets** [comment]
@schams-net I probably agree with most of what you wrote in practices. But what you wrote also feels a little like giving the original author most of the credit and valuing the work of both ➀ and  ➁ more than ➂ or what you call "community work". And I see a problem and a danger in doing that:

Please consider that both ➁ and  ➂ are (mostly) highly unrewarding work (in my opinion). It might be fun for some, but personally I don't enjoy doing it very much in the long run. I do it because I think it is useful and somebody must do it and at the beginning it was fun and I learned a lot. I also think we need more people for this. If writing manuals is considered to be "more important" work where the author is named and maintaining / improving etc. manuals is not - I think you get what I am trying to say: we need more people to actually improve and maintain manuals and keep them in good shape, so we should try to acknowledge the contribution and value of this work. And I wouldn't even start comparing the value of authoring and maintaining / improving / reviewing because that is a very slippery slope. That way we start to have 2 classes of people: the _stars_ who are named personally and the _community people_ (aka _useful idiots_) who get a pat on the back, no money and will quickly retreat back to an area of contribution in TYPO3 or some other open source project where they get more equal treatment or they don't contribute at all. 

I think you made a great contribution with the site package tutorial, pls don't misunderstand my intentions here!!! But what you wrote does not make me want to contribute more. It makes me want to say: let other people do the tedious grunge work now (like reviewing, fixing spelling mistakes, merging patches, improving patches, commenting issues, closing issues etc.) because it's fun for a while but after a while it's not fun enough to continually spend lots of time on this for no money (and little or no credit). 

Actually, I think this is an important aspect of contributing to TYPO3 in general. How do you keep everyone motivated if some work gets paid and acknowledged and other work does not? Seems to work for the TYPO3 core where you have a mix of paid and unpaid contribution work.

**Comment by sypets** [comment]
@schams-net Is this your personal opinion or is this official policy? 

I have a problem with this statement because it is based on how a book would be done but not how TYPO3 documentation currently works. A lot (or most) of the work is done by several contributors and mergers. A significant part of the work has been updated, rewritten and refined over the years. Having an author doing 99% of the work, with a few minor fixes for the next release - that is rarely the case here. TYPO3 Explained has 150 contributors listed via GitHub. Indiviual chapters have been added by various people. If this document listed an original author on the front page, would that now still be justified? And to make the question even more difficult - what if the original work submitted was only mediocre and someone considerably improves the work making it more readable. That person would be group 2, I guess. The original author would be group 1. What if it wasn't one person but 50 - each one improving a small but considerable amount, all in all resulting in a manual that transistioned from bad or mediocre to great. The group would be group 3, right? (this is a theoretical example - I am not talking about a specific manual).

And who decides what is a significant improvement?

The nature of our open source collaborative work makes these questions more difficult. 

I think attribution (crediting, acknowledgement) is an important incentive. And I am unsure about a 3-class system, especially if it gives more credit (and more value) to work that may not even be the decicive factor in making a manual really great (in case we ever do get there).

A lot of the original work has been considerably refined. This no longer warrants crediting the author as author, the contributors in "Acknowledgements" and others not at all.

If the suggested 3 levels of "importance" is implemented, the group 3 will not be credited at all. If we regard credit as an important incentive for contribution, why should people keep doingt the work that is not to be credited?

Not crediting someone for some work (while others do get credited) - does this value the work less? I think it does.

Merging PR, updating documentation, restructuring documentation, deduplicating content in various places has been an important part of improving the docs, especially recently. If this is regarded as not so important, I find these extremely demotivating and not very respectful towards the people who have put in hours and hours into this work. _Especially_ if they did it for free. Not everyone wants to be publicly listed. This may not be important for everyone. Others may not even want to be associated with the docs, because the docs are not always of sufficient quality. But I have a big problem with differentiating in this way.

If the original author has really done 99% of the work and 2 or three people just make 2 or 3 changes, ok, in this case I might agree. But our reality looks very much different.

And there is also the task of merging PR day in day out. This is fun in the beginning. But soon becomes a chore. 

It is a little like giving all the credit to the people who put up garbage pails throught the city. And then just taking for granted the  people who empty them week after week, keep them clean and dispose of the garbage. One without the other would be useless. But why give all the credit to just one group?

**Comment by linawolf** [comment]
I think this is not relevant anymore
