### ISSUE TITLE
Create an automated solution for viewhelper reference

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/T3DocTeam#9]
# More information

* See also initial issue in Extbase / Fluid guide repo: https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-Extbase/issues/100
* Claus Due Schemamaker: https://github.com/FluidTYPO3/schemaker
* list of viewhelpers on fluidtypo3.org: https://fluidtypo3.org/viewhelpers.html
* manually maintained list of TYPO3 viewhelpers: https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Index.html

**Comment by DanielSiepmann** [comment]
If no one want to tackle that, I could give it a try. Maybe this is something for @randomresult, so he has a long running task he can work on ;)

Also we might ask @NamelessCoder to share his code for rendering https://fluidtypo3.org/viewhelpers.html.

**Comment by sypets** [comment]
@DanielSiepmann Tymotheusz had some ideas, check with him as well.

**Comment by NamelessCoder** [comment]
Don't waste time here - a static site generator will come. I'll set up an instance that allows pushing new XSD files over http, then you just need to generate that file and automate a push in the release generation logic.

**Comment by DanielSiepmann** [comment]
@NamelessCoder are you willing to integrate that into docs.typo3.org? Because this should be an official documentation, at least for the TYPO3 core.
And as we have the extension repository, we might integrate this process also for all extensions and their releases.

**Comment by NamelessCoder** [comment]
@DanielSiepmann If TYPO3 wants to host this, that will be possible. But I intend to integrate this in a way that lets extension authors:

1. Gain access to pushing XSD files for their repositories
2. Automate the pushing of these XSD files by things like Travis
3. Author special documentation index files that describe the package, vendor etc.

If you want to avoid all the maintenance and setup plus hosting the solution I don't mind doing this. In that case you could just forward for example `typo3.org/viewhelpers` to that site.

To tease a bit, the static generated site will be completely relative with URLs so it will work even if you generate it locally and open the index.html in a browser. It will in addition also provide a navigatable JSON version of the docs which make it possible to use it as remote for any purpose.

FYI: I would not allow generating of XSD files as automation on our servers, since that involves executing PHP code that could potentially be used to exploit things. Instead, by demanding that the XSD get generated by the extension author, but that this can be automated easily, appears to be the safest option and it's the one I'm going for. And then it doesn't matter where the repository exists or if it is even on TER at all.

**Comment by NamelessCoder** [comment]
The static site generation tool I talked about is finished. Or rather, the parts that generate the documentation are done - it still has no companion application that allows registered users to manage their schemas and metadata.

https://github.com/NamelessCoder/fluid-documentation-generator

See README there for description of capabilities.

**Comment by marble** [comment]
From [Slack](https://typo3.slack.com/archives/C028JEPJL/p1533307815000412):

Tymoteusz Motylewski [4:50 PM]
here is the demo of the tool we're using to generate the reference https://viewhelpers.fluidtypo3.org/typo3/cms-fluid/7.6.0/
(in our case we will only include core viewhelpers, not the one from extensions)
Here is an issue about replacing viewhelper reference: https://github.com/TYPO3-Documentation/T3DocTeam/issues/9 (edited)

How we do it:
1) generate xsd schema from TYPO3 core using https://github.com/TYPO3/Fluid.SchemaGenerator
2) generate html from xsd schema using https://github.com/NamelessCoder/fluid-documentation-generator (edited)

**Comment by marble** [comment]
Some questions and thoughts:

1. Just asking, as I don't understand the details yet: Is the reference based on the PHP code or based on the comments in PHP code? In other words: Will it be a correct documentation automatically?

2. Can we make it look more like TYPO3 documentation?

3. IMHO it should be located at https://docs.typo3.org/typo3cms/extensions/fluid/viewhelpers

**Comment by NamelessCoder** [comment]
> Just asking, as I don't understand the details yet: Is the reference based on the PHP code or based on the comments in PHP code? In other words: Will it be a correct documentation automatically?

It is both. The XSD is generated based on PHP classes and the ViewHelper description comes from the PHPDoc comment - the arguments on the other hand come from executing PHP. It will be as correct as those parts are ;)

The tool I wrote renders markdown and the CMS core ViewHelpers use a rather bad mix of RST and HTML that isn't indented. That results in a rather weird rendering. If you want, you can replace the markdown rendering with RST but I'd recommend moving away from RST+HTML in the PHPDoc, over to Markdown which is a whole lot easier to handle.

> Can we make it look more like TYPO3 documentation?

Absolutely. The HTML is generated with Fluid and the templates are of course included. The styles can be replaced in the public assets folder.

> IMHO it should be located at https://docs.typo3.org/typo3cms/extensions/fluid/viewhelpers

Might not be possible to do if part of the requirement is to automate this at some point. Personally I don't agree since these are TER docs and TER is for third-party extensions, but that's kind of beside the point :)

By the way: the tool I wrote spits out HTML and JSON, but there's no reason why you couldn't make it spit out Markdown or RST files that can then be rendered by another system. It can do all of it at the same time as well - HTML, JSON, RST and MD if you'd like. It only requires a custom "exporter" implementation using `fluid-documentation-generator`.

**Comment by marble** [comment]
@NamelessCoder Cool. Thanks for the explanations. It seems with joined forces we'll find a great solution.

About the location of that viewhelper reference: We are using https://docs.typo3.org/typo3cms/extensions/EXTKEY for ALL extensions, no matter if system extension or TER extension. That may have become a bit unclear through recent changes in the surrounding texts on docs.typo3.org. I'm afraid some menu items are misleading at the moment.

**Comment by tmotyl** [comment]
@marble I see a big drawback of rendering all viewhelper references separately for every core extension under different url. It will be much harder for the developer to find viewhelper when he has to go through many extensions.
When I'm e.g. developing a module for TYPO3, I would like to have one reference with all viewhelpers from all core extensions.
Because as a developer I don't care much whether the viewhelper is in Core extension or in Fluid extension or Backend.

I propose to either have it as a part of the core api, or as a separate reference.

**Comment by sypets** [comment]
+1 for **one** viewhelper reference.

**Comment by marble** [comment]
@tmotyl 
?
I think you got me wrong. Maybe because you know things about the core I don't know. I certainly don't mean to scatter the viewhelper reference around.

My question is: What should be the url of the generated viewhelper reference at docs.typo3.org?

**Comment by tmotyl** [comment]
I'm thinking about 
https://docs.typo3.org/typo3cms/viewhelperreference
or
https://docs.typo3.org/typo3cms/CoreApiReference/viewhelperreference

**Comment by sypets** [comment]
Suggestion: Wait for a concept / draft for developer documentation structure in general, before this is decided. I will raise the issue in Slack.

**Comment by susannemoog** [comment]
@tmotyl we'd have to add an @api tag or something similar then, as I don't want an extension developer to use the viewhelpers of belog or beuser module but rather only the ones in either core, fluid or backend (which should probably be consolidated, too). In short: not every core viewhelper is API imho.

**Comment by NamelessCoder** [comment]
If I may make a suggestion: given that some ViewHelpers (identified by their context, e.g. the system extension) are not public API, the logical decision seems to document those ViewHelpers that *are* public API in one place, and document the remaining non-API ViewHelpers elsewhere.

Call it core developer specific documentation.

And forgive the tangent, but part of the reason why these ViewHelpers aren't considered API is, I would say, that the template files of many particularly backend modules' collections *cannot be overridden because the TemplateViews are used in a less than ideal way*, meaning they wrap two views inside each other and the outer view isn't Fluid-aware and doesn't support normal Fluid overrides - and the inner view is provided with a hardcoded template file path in almost all cases.

If this were to be corrected, and I'd recommend that it does get corrected some day, then those ViewHelpers that are used in those templates become at least semi-API.

My point is: it may not be wise to begin creating two sets of documentation, one for end users and one for core developers. I even lean towards then not documenting the non-API ViewHelpers at all (under the assumption that anyone working on core development knows how to look this up in the class itself).

**Comment by tmotyl** [comment]
@psychomieze ok, so it looks that putting it as a separate url is a better idea then integrating it into coreAPI.
I would still like to have one reference listing all viewheleprs from the core, even if they are not an api. This way it's easier to find and see how core implemented something and do my own implementation ispired by this.

**Comment by tmotyl** [comment]
@marble is the decision on the url already taken?

**Comment by DanielSiepmann** [comment]
We already discusses the future URL structure of docs.typo3.org back at the first meeting with the Core Team this year and came up with the following:

```
t3SphinxThemesRtd/3.6/ … javascript … css  (that is the _static folder)
/p/{vendor}/{extension}/master/
/p/ringer/news/8.7/  (“extensions”, type: typo3-cms-extension)
/p/ringer/news/drafts/ (linked as “there is a draft version”, has robots.txt no index, maybe has directory listing turned on)
/c/typo3/cms-beuser/8.7/  (“core extensions”, type: typo3-cms-framework)
/m/typo3 (?)/coreapi/master/ (“typo3 docs”, type: typo3-cms-documentation, example: coreapi, walkthrough, …)
```

So, this should fit in this structure. Also we should add this to the Bamboo concept of rendering everything.

**Comment by DanielSiepmann** [comment]
As discussed with @tmotyl I've created https://github.com/TYPO3-Documentation/viewhelper-reference for a first solution to get started and to move things forward.

I'm in charge for the documentation team and communication happens via Slack.

**Comment by sypets** [comment]
Is implemented: https://docs.typo3.org/News/2018/Index.html#news-2018-11-05
